on:
  fork:

  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: build

jobs:
  phpunit:
    if: github.event.repository.fork == true || (github.event_name == 'push' && github.ref == 'refs/heads/master') || (github.event_name == 'pull_request')
    uses: yiisoft/actions/.github/workflows/phpunit.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
